package com.example.gpssportmap

object Constants {
    const val LOCATION_UPDATE_ACTION = "locationUpdate"
    const val LOCATION = "location"
    const val ADD_WAYPOINT_ACTION = "ADD_WAYPOINT_ACTION"
    const val ADD_MARKER_ACTION = "ADD_MARKER_ACTION"
    const val MAIN_NOTIFICATION_ID = 1
    const val APP_CHANNEL_NAME = "APP_CHANNEL_NAME"
    const val APP_CHANNEL_ID = "APP_CHANNEL_ID"
    const val SEND_MAP_BRAIN_ACTION = "SEND_MAP_BRAIN_ACTION"
    const val MAP_BRAIN = "MAP_BRAIN"

    const val SESSION_TIMER_ACTION = "SESSION_TIMER_ACTION"
    const val SESSION_TIME = "SESSION_TIME"
    const val MARKER_TIMER_ACTION = "MARKER_TIMER_ACTION"
    const val MARKER_TIME = "MARKER_TIME"
    const val WAYPOINT_TIMER_ACTION = "WAYPOINT_TIMER_ACTION"
    const val WAYPOINT_TIME = "WAYPOINT_TIME"

    const val MARKER_CLICK_ACTION_NOT = "MARKER_CLICK_ACTION_NOT"
    const val WAYPOINT_CLICK_ACTION_NOT = "WAYPOINT_CLICK_ACTION_NOT"

    const val MARKER_CLICK_ACTION = "MARKER_CLICK_ACTION"
    const val WAYPOINT_CLICK_ACTION = "WAYPOINT_CLICK_ACTION"

    const val WAYPOINT_BROADCAST_VALUE = "WAYPOINT_BROADCAST_VALUE"

    const val ASK_FOR_CACHED_BRAIN_ACTION = "ASK_FOR_CACHED_BRAIN_ACTION"

    const val LATITUDE = "LATITUDE"
    const val LONGITUDE = "LONGITUDE"

    const val SAVE_COMPLETED_SESSION_ACTION = "SAVE_COMPLETED_SESSION_ACTION"
    const val COMPLETED_SESSION_NAME = "COMPLETED_SESSION_NAME"

    const val SESSION_ID = "SESSION_ID"

    const val USER_TOKEN_PREF_KEY = "USER_TOKEN_PREF_KEY"
    const val USER_EMAIL_PREF = "USER_EMAIL_PREF"
    const val USER_PASSWORD_PREF = "USER_PASSWORD_PREF"
    const val USER_FIRST_NAME_PREF = "USER_FIRST_NAME_PREF"
    const val USER_LAST_NAME_PREF = "USER_LAST_NAME_PREF"

    const val GPS_LOCATION_TYPE_LOC_ID = "00000000-0000-0000-0000-000000000001"
    const val GPS_LOCATION_TYPE_WP_ID = "00000000-0000-0000-0000-000000000002"
    const val GPS_LOCATION_TYPE_CP_ID = "00000000-0000-0000-0000-000000000003"
}